#################################################################################
#                               OneBranch Pipelines                             #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

trigger: none

variables:
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)] # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  LinuxContainerImage: 'onebranch.azurecr.io/linux/ubuntu-2004:latest' # Docker image which is used to build the project https://aka.ms/obpipelines/containers
  WindowsContainerImage: 'onebranch.azurecr.io/windows/ltsc2019/vse2022:latest'

resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    globalSdl: # https://aka.ms/obpipelines/sdl
      policheck:
        break: true # always break the build on policheck issues.
      binskim:
        enabled: false # Temporarily disable binskim until we sort out BA2018 errors

    stages:
    - stage: Build_Windows
      displayName: Build Windows
      jobs:
      - template: .pipelines/templates/build-windows.yml@self
        parameters:
          arch: 'AMD64'
          config: 'Debug'
      - template: .pipelines/templates/build-windows.yml@self
        parameters:
          arch: 'AMD64'
          config: 'Release'
      - template: .pipelines/templates/build-windows.yml@self
        parameters:
          arch: 'X86'
          config: 'Debug'
      - template: .pipelines/templates/build-windows.yml@self
        parameters:
          arch: 'X86'
          config: 'Release'
      - template: .pipelines/templates/build-windows.yml@self
        parameters:
          arch: 'AMD64'
          config: 'Release'
          additionalArgs: '--no-asm'
          identifier: 'NoAsm'
      - template: .pipelines/templates/build-windows.yml@self
        parameters:
          arch: 'X86'
          config: 'Release'
          additionalArgs: '--no-asm'
          identifier: 'NoAsm'

    - stage: Build_Linux
      displayName: Build Linux
      jobs:
      - template: .pipelines/templates/build-linux.yml@self
        parameters:
          arch: 'AMD64'
          config: 'Debug'
          cc: 'gcc'
          cxx: 'g++'
      - template: .pipelines/templates/build-linux.yml@self
        parameters:
          arch: 'AMD64'
          config: 'Sanitize'
          cc: 'gcc'
          cxx: 'g++'
      - template: .pipelines/templates/build-linux.yml@self
        parameters:
          arch: 'AMD64'
          config: 'Release'
          cc: 'gcc'
          cxx: 'g++'          
      - template: .pipelines/templates/build-linux.yml@self
        parameters:
          arch: 'AMD64'
          config: 'Debug'
          cc: 'clang'
          cxx: 'clang++'
      - template: .pipelines/templates/build-linux.yml@self
        parameters:
          arch: 'AMD64'
          config: 'Sanitize'
          cc: 'clang'
          cxx: 'clang++'
      - template: .pipelines/templates/build-linux.yml@self
        parameters:
          arch: 'AMD64'
          config: 'Release'
          cc: 'clang'
          cxx: 'clang++'
      - template: .pipelines/templates/build-linux.yml@self
        parameters:
          arch: 'AMD64'
          config: 'Release'
          cc: 'gcc'
          cxx: 'g++'
          additionalArgs: '--no-asm'
          identifier: 'NoAsm'
      - template: .pipelines/templates/build-linux.yml@self
        parameters:
          arch: 'AMD64'
          config: 'Release'
          cc: 'clang'
          cxx: 'clang++'
          additionalArgs: '--no-asm'
          identifier: 'NoAsm'
      - template: .pipelines/templates/build-linux.yml@self
        parameters:
          arch: 'X86'
          config: 'Release'
          cc: 'gcc'
          cxx: 'g++'
          additionalArgs: '--no-asm --no-fips'
          identifier: 'NoAsm'
      - template: .pipelines/templates/build-linux.yml@self
        parameters:
          arch: 'ARM64'
          config: 'Debug'
          cc: 'clang'
          cxx: 'clang++'
          additionalArgs: '--toolchain=cmake-configs/Toolchain-Clang-ARM64.cmake'
      - template: .pipelines/templates/build-linux.yml@self
        parameters:
          arch: 'ARM64'
          config: 'Release'
          cc: 'clang'
          cxx: 'clang++'
          additionalArgs: '--toolchain=cmake-configs/Toolchain-Clang-ARM64.cmake'