[package]
name = "symcrypt-sys"
authors = ["nnmkhang"]
version = "0.1.0"
license = "MIT OR Apache-2.0"
description = "Rust/C Bindings for SymCrypt"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.0"
