[package]
name = "symcrypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
symcrypt-sys = {path = "../symcrypt-sys"}
libc = "0.2.0"
lazy_static = "1.4.0"

[dev-dependencies]
hex = "0.4.3"
